#define Z_NEAR 10.f
#define Z_FAR 10000.0f

//#define Z_NEAR 5.f
//#define Z_FAR 500.0f

#define RIGHT 1.f
#define LEFT -RIGHT
#define TOP 1.f
#define BOTTOM -TOP

// SPHERE ACCELERATION STRUCTURE
#define SPHERE_ACCELERATION_STRUCTURE_STEP_SIZE 10

#define DEFAULT_HOUR_OF_DAY 12
#define DEFAULT_MONTH_OF_YEAR 6
